version: 2
jobs:
  test-python2.7:
    docker:
      - image: circleci/python:2.7.16-browsers
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            mkdir -p ./venv
            virtualenv ./venv
            . venv/bin/activate
            pip install tox
      - run:
          name: Run unit tests
          command: |
            . venv/bin/activate
            tox -e unit
          when: always
      - run:
          name: Run integration tests
          command: |
            . venv/bin/activate
            tox -e integration
          when: always
  test-python3.6:
    docker:
      - image: circleci/python:3.6.8-browsers
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            mkdir -p ./venv
            virtualenv ./venv
            . venv/bin/activate
            pip install tox
      - run:
          name: Run unit tests
          command: |
            . venv/bin/activate
            tox -e unit
          when: always
      - run:
          name: Run integration tests
          command: |
            . venv/bin/activate
            tox -e integration
          when: always
  quality:
    docker:
      - image: circleci/python:2.7.16
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            mkdir -p ./venv
            virtualenv ./venv
            . venv/bin/activate
            pip install tox pylint
      - run:
          name: Run integration tests
          command: |
            . venv/bin/activate
            tox -e quality
          when: always
workflows:
  version: 2
  build:
    jobs:
      - test
      - quality
