version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.5-browsers
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            mkdir -p ./venv
            virtualenv ./venv
            . venv/bin/activate
            pip install tox
      - run:
          name: Run unit tests
          command: |
            . venv/bin/activate
            tox -e unit
          when: always
      - run:
          name: Run integration tests
          command: |
            . venv/bin/activate
            tox -e integration
          when: always
  quality:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            mkdir -p ./venv
            virtualenv ./venv
            . venv/bin/activate
            pip install tox pylint
      - run:
          name: Run python3 quality tests
          command: |
            . venv/bin/activate
            tox -e python3-quality
          when: always
workflows:
  version: 2
  build:
    jobs:
      - test
      - quality
